export const portfolioPreferenceUNHRC = [
  "Afghanistan",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Benin",
  "Brazil",
  "Burundi",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Costa Rica",
  "Côte d'Ivoire",
  "Cuba",
  "Czech Republic",
  "Eritrea",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "India",
  "Indonesia",
  "Iran",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Kuwait",
  "Lithuania",
  "Luxembourg",
  "Malawi",
  "Maldives",
  "Mexico",
  "Montenegro",
  "Nepal",
  "Netherlands",
  "Norway",
  "Pakistan",
  "Paraguay",
  "Philippines",
  "Poland",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Senegal",
  "Somalia",
  "South Africa",
  "South Korea",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Tajikistan",
  "Turkey",
  "Turkmenistan",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vietnam"
];
