export const AISM = [
  "Nitish Kumar - Chief Minister of Bihar",
  "Tejashwi Yadav - Deputy Chief Minister of Bihar",
  "Chirag Paswan - Leader of Lok Janshakti Party",
  "Mayawati - Former Chief Minister of Uttar Pradesh and BSP Leader",
  "Hemant Soren - Chief Minister of Jharkhand",
  "Naveen Patnaik - Former Chief Minister of Odisha and Leader of BJD",
  "Rahul Gandhi - Leader of the opposition in Lok Sabha",
  "H.D. Deve Gowda - Former Prime Minister of India and Rajya Sabha Member",
  "Jagan Mohan Reddy - Chief Minister of Andhra Pradesh",
  "Pinarayi Vijayan - Chief Minister of Kerala",
  "Amit Shah - Minister of Home Affairs",
  "Akhilesh Yadav - Former Chief Minister of Uttar Pradesh and Samajwadi Party Leader",
  "Shivraj Singh Chouhan - Chief Minister of Madhya Pradesh",
  "Arjun Ram Meghwal - Union Minister of Law and Justice",
  "Ramdas Athawale - Minister of State for Social Justice and Empowerment",
  "Kantilal Bhuria - Politician and Former Union Minister of Tribal Affairs",
  "Mallikarjun Kharge - Leader of Opposition in Rajya Sabha",
  "Shashi Tharoor - Member of Parliament and Author",
  "Smriti Irani - Union Minister of Women and Child Development",
  "Nirmala Sitharaman - Union Finance Minister",
  "Chandrashekhar Azad - Dalit Activist and Politician",
  "Soni Sori - Tribal Activist",
  "Dayamani Barla - Tribal Rights Activist",
  "Archana Soreng - Climate and Tribal Rights Activist",
  "Gladson Dungdung - Tribal Activist and Author",
  "Nand Kumar Sai - Former Chairperson of National Commission for Scheduled Tribes (NCST)",
  "Shruti Nagvanshi - Human Rights Activist",
  "Chami Murmu - Environmentalist and Tribal Advocate",
  "Aruna Roy - Social Activist",
  "Medha Patkar - Activist and Founder of Narmada Bachao Andolan",
  "Bezwada Wilson - Activist and Founder of Safai Karamchari Andolan",
  "Harsh Mander - Social Worker and Author",
  "Kailash Satyarthi - Nobel Laureate and Child Rights Activist",
  "Laxmi Narayan Tripathi - Transgender Rights Activist",
  "Satish Prasad - Grassroots Activist for Rural Development",
  "Ranjan Gogoi - Former Chief Justice of India",
  "U.U. Lalit - Former Chief Justice of India",
  "D.Y. Chandrachud - Chief Justice of India",
  "Rajeev Dhavan - Senior Advocate and Constitution Expert",
  "Indira Jaising - Senior Advocate and Human Rights Lawyer",
  "Menaka Guruswamy - Senior Advocate and LGBTQ+ Rights Activist",
  "Arvind Datar - Senior Advocate and Taxation Expert",
  "P. Sainath - Journalist and Rural Affairs Expert",
  "Ravish Kumar - Journalist and News Anchor",
  "Smita Prakash - Journalist and Editor",
  "Sudhir Chaudhary - Journalist and Editor",
  "Karan Thapar - Journalist and Political Analyst",
  "Rajdeep Sardesai - Journalist and Author",
  "Anjana Om Kashyap - Journalist and Anchor",
  "Paranjoy Guha Thakurta - Investigative Journalist",
  "Prof. Dipankar Gupta - Sociologist",
  "Dr. Gail Omvedt - Sociologist and Author (Posthumous Influence)",
  "Dr. Ashwini Deshpande - Economist and Social Researcher",
  "Dr. P. Arokiasamy - Demographer and Public Policy Expert",
  "Prof. Yogendra Yadav - Political Scientist and Activist",
  "Kancha Ilaiah Shepherd - Social Scientist and Author",
  "Anand Teltumbde - Scholar and Activist",
  "Jean Drèze - Economist and Social Policy Expert",
  "Suraj Yengde - Scholar and Dalit Activist",
  "Chandra Bhan Prasad - Dalit Entrepreneur and Writer",
  "Vivek Kumar - Professor and Sociologist",
  "Badri Narayan - Historian and Social Scientist",
  "Sukhadeo Thorat - Economist and Former Chairperson, UGC",
  "Anuradha Chenoy - International Relations and Gender Studies Expert",
  "Dr. Sandeep Pandey - Educationist and Activist",
  "Azim Premji - Industrialist and Philanthropist",
  "Anand Mahindra - Industrialist",
  "N. Chandrasekaran - Chairman of Tata Sons",
  "Narayana Murthy - Founder of Infosys and Philanthropist",
  "Sudha Murty - Author and Chairperson, Infosys Foundation",
  "Vineet Nayar - Philanthropist and Founder of Sampark Foundation",
  "Kiran Mazumdar-Shaw - Entrepreneur and Chairperson of Biocon",
  "Dr. Virendra Kumar - Union Minister of Social Justice and Empowerment",
  "Shri Kishor Makwana - Chairperson of National Commission for Scheduled Castes (NCSC)",
  "Shri Hansraj Gangaram Ahir - Chairperson of National Commission for Backward Classes (NCBC)",
  "Dr. Rajiv Kumar - Economist and Former Vice Chairman, NITI Aayog",
  "Dr. Pratap Bhanu Mehta - Political Scientist and Academic",
  "Dr. S.Y. Quraishi - Former Chief Election Commissioner of India",
  "Raja Sekhar Vundru - Bureaucrat and Author on Social Justice",
  "Deepa Narayan - Development Consultant and Author",
  "N.C. Saxena - Former Planning Commission Member",
  "Abhijit Banerjee - Nobel Laureate in Economics",
  "M.S. Swaminathan - Agricultural Scientist (Posthumous Influence)",
  "Dr. Vandana Shiva - Environmental Activist and Author",
  "Devinder Sharma - Agricultural Policy Expert",
  "Sunita Narain - Environmentalist and Director, CSE",
  "Ramesh Chand - Economist and Agricultural Policy Maker",
  "Dr. Vivek Joshi - Bureaucrat and Policy Maker",
  "Yogesh Kumar - CEO, Samarthan NGO",
  "Parmesh Shahani - LGBTQ+ Advocate and Author",
  "R. Gopalakrishnan - Author and Management Thinker",
  "Bhavish Aggarwal - CEO and Co-founder, Ola",
  "Falguni Nayar - Founder, Nykaa",
  "Rohini Nilekani - Philanthropist and Chairperson, Arghyam Foundation",
  "Dr. Shamika Ravi - Economist and Public Policy Expert",
  "Nisha Agrawal - Former CEO, Oxfam India",
  "Anshu Gupta - Founder, Goonj",
  "Shaheen Mistri - Founder, Teach for India",
  "Reetika Khera - Economist and Public Policy Researcher"
];
