export const DISEC = [
  "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
  "Armenia", "Australia", "Austria", "Bahrain", "Bangladesh", "Barbados",
  "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Botswana",
  "Brazil", "Brunei", "Burkina Faso", "Burundi", "Cambodia", "Canada",
  "Cape Verde", "Central African Republic", "Chad", "Chile", "China",
  "Comoros", "Congo (Republic of the Congo)", "Costa Rica", "Croatia",
  "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
  "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
  "Eswatini", "Ethiopia", "Finland", "France", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
  "Guinea-Bissau", "Haiti", "Holy See (Vatican City)", "Hungary", "Iceland",
  "India", "Indonesia", "Iran", "Iraq", "Israel", "Italy", "Jamaica",
  "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo",
  "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Liechtenstein",
  "Lithuania", "Luxembourg", "Malawi", "Malaysia", "Maldives", "Mexico",
  "Micronesia", "Mongolia", "Morocco", "Mozambique", "Myanmar", "Namibia",
  "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Nigeria", "North Macedonia",
  "Norway", "Oman", "Pakistan", "Palau", "Panama", "Paraguay", "Peru", "Poland",
  "Portugal", "Qatar", "Republic of the Congo", "Romania", "Rwanda",
  "São Tomé and Príncipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Singapore", "Slovakia", "Slovenia", "Somalia", "South Africa", "South Korea",
  "Spain", "Sri Lanka", "Sudan", "Sweden", "Switzerland", "Syria",
  "Tajikistan", "Tanzania", "Timor-Leste", "Togo", "Trinidad and Tobago",
  "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];
