export const PortfolioPreferencesAippm = [
  "Rajiv Kumar - Chief Election Commissioner",
  "Arvind Kejriwal - Aam Admi Party",
  "Sanjay Singh - Aam Admi Party",
  "Raghav Chadha - Aam Admi Party",
  "Bhagwant Mann - Aam Admi Party",
  "Atishi Marlena - Aam Admi Party",
  "Manish Sisodia - Aam Admi Party",
  "Asaduddin Owaisi - All India Majlis-e-Ittehad-ul-Muslimeen",
  "Imtiaz Jaleel - All India Majlis-e-Ittehad-ul-Muslimeen",
  "Akhtarul Iman - All India Majlis-e-Ittehad-ul-Muslimeen",
  "Mamta Banerjee - All India Trinamool Congress",
  "Abhishek Banerjee - All India Trinamool Congress",
  "Derek O'Brien - All India Trinamool Congress",
  "Mahua Moitra - All India Trinamool Congress",
  "Kunwar Danish Ali - Bahujan Samaj Party",
  "Kumari Mayawati - Bahujan Samaj Party",
  "Narendra Modi - Bharatiya Janata Party",
  "Amit Shah - Bharatiya Janata Party",
  "Dharmendra Pradhan - Bharatiya Janata Party",
  "Ashwini Vaishnaw - Bharatiya Janata Party",
  "Bhupinder Patel - Bharatiya Janata Party",
  "Hardeep Singh Puri - Bharatiya Janata Party",
  "Kiren Rijiju - Bharatiya Janata Party",
  "Manoharlal Khattar - Bharatiya Janata Party",
  "Manoj Tiwari - Bharatiya Janata Party",
  "Anurag Singh Thakur - Bharatiya Janata Party",
  "Nirmala Sitharaman - Bharatiya Janata Party",
  "Nitin Gadkari - Bharatiya Janata Party",
  "Piyush Goyal - Bharatiya Janata Party",
  "Rajnath Singh - Bharatiya Janata Party",
  "Shivraj Singh Chouhan - Bharatiya Janata Party",
  "Smriti Irani - Bharatiya Janata Party",
  "Subramanyam Jaishankar - Bharatiya Janata Party",
  "Sudhanshu Trivedi - Bharatiya Janata Party",
  "Tejaswi Surya - Bharatiya Janata Party",
  "Vasundhara Raje - Bharatiya Janata Party",
  "Yogi Adityanath - Bharatiya Janata Party",
  "Maneka Gandhi - Bharatiya Janata Party",
  "Meenakshi Lekhi - Bharatiya Janata Party",
  "G Kishan Reddy - Bharatiya Janata Party",
  "Jyotiraditya Scindia - Bharatiya Janata Party",
  "Dr Mansukh Mandaviya - Bharatiya Janata Party",
  "Himanta Biswa Sarma - Bharatiya Janata Party",
  "Hardik Patel - Bharatiya Janata Party",
  "Pema Khandu - Bharatiya Janata Party",
  "J.P. Nadda - Bharatiya Janata Party",
  "Prahlad Joshi - Bharatiya Janata Party",
  "Diya Kumari - Bharatiya Janata Party",
  "Annamalai - Bharatiya Janata Party",
  "Arjun Ram Meghwal - Bharatiya Janata Party",
  "Devendra Fadnavis - Bharatiya Janata Party",
  "Navneet Kaur Rana - Bharatiya Janata Party",
  "Naveen Patnaik - Biju Janata Dal",
  "D. Raja - Communist Party of India",
  "Pinarayi Vijayan - Communist Party of India (Marxist)",
  "M. K. Stalin - Dravida Munnetra Kazhagam",
  "K. Karunanidhi - Dravida Munnetra Kazhagam",
  "Naba Kumar Sarania - Independent",
  "Ranjan Gogoi - Independent",
  "Umesh Kumar - Independent",
  "Kapil Sibal - Independent",
  "Chandrashekhar Azad Ravan - Independent",
  "Mohammad Haneefa - Independent",
  "Sheikh Abdul Rashid - Independent",
  "Rahul Gandhi - Indian National Congress",
  "Sonia Gandhi - Indian National Congress",
  "Priyanka Gandhi Vadra - Indian National Congress",
  "Sachin Pilot - Indian National Congress",
  "Dr. Shashi Tharoor - Indian National Congress",
  "Dr. Manmohan Singh - Indian National Congress",
  "Ashok Gehlot - Indian National Congress",
  "Adhir Ranjan Chowdhury - Indian National Congress",
  "Bhupesh Baghel - Indian National Congress",
  "Mallikarjun Kharge - Indian National Congress",
  "Dr. Abhishek Manu - Indian National Congress",
  "Bhupinder Singh Hooda - Indian National Congress",
  "Imran Pratapgarhi - Indian National Congress",
  "Jairam Ramesh - Indian National Congress",
  "Ajay Maken - Indian National Congress",
  "Kanhaiya Kumar - Indian National Congress",
  "Shanti Dhariwal - Indian National Congress",
  "Siddaramaiah - Indian National Congress",
  "Omar Abdullah - Jammu and Kashmir National Congress",
  "Farooq Abdullah - Jammu and Kashmir National Congress",
  "Mehbooba Mufti - Jammu and Kashmir People's Democratic Party",
  "Prashant Kishore - Jan Suraj",
  "Pawan Kalyan - Janasena Party",
  "HD Deve Gowda - Janata Dal (Secular)",
  "Nitish Kumar - Janta Dal",
  "S. Ambreesh - Janta Dal",
  "Hemant Soren - Jharkhand Mukti Morcha",
  "Chirag Paswan - Lok Janshakti Party(Ram Vilas)",
  "Raj Thackeray - Maharashtra Navnirman Sena",
  "Conrad Sangma - National People's Party",
  "Ajit Pawar - Nationalist Congress Party",
  "Praful Patel - Nationalist Congress Party",
  "Sharad Pawar - Nationalist Congress Party",
  "Supriya Sule - Nationalist Congress Party",
  "Neiphiu Rio - Nationalist Democratic Progressive Party",
  "Shri Suman K. Bery - NITI Ayog Vice-Chain",
  "Lalu Prasad Yadav - Rashtriya Janta Dal",
  "Manoj Jha - Rashtriya Janta Dal",
  "Rabri Devi - Rashtriya Janta Dal",
  "Tejashwi Yadav - Rashtriya Janta Dal",
  "Akhilesh Yadav - Samajwadi Party",
  "Ram Gopal Yadav - Samajwadi Party",
  "S.T. Hasan - Samajwadi Party",
  "Sukhbir Singh Badal - Shiromani Akali Dal",
  "Harsimrat Kaur Badal - Shiromani Akali Dal",
  "Eknath Shinde - Shiv Sena",
  "Sanjay Raut - Shiv Sena(UBT)",
  "Uddhav Thackeray - Shiv Sena(UBT)",
  "Prem Singh Tamang - Sikkim Krantikari Morcha",
  "Yogendra Yadav - Swaraj India Party",
  "Nara Chandrababu Naidu - Telugu Desam Party",
  "Jagan Mohan Reddy - YSR Congress Party"
]

